[[projects]]
source = "https://github.com/example/project1"
platform = "Aws"
language = { Rust = "Rocket" }
database = "PostgreSQL"
deployment = "DockerCompose"

[[projects]]
source = "https://github.com/example/project2"
platform = "Vercel"
language = { Javascript = "React" }
database = "MySql"
deployment = "Terraform"

[[projects]]
source = "https://github.com/example/project3"
language = { CSharp = {} }
database = "DynamoDB"

[[projects]]
source = "https://github.com/example/project4"
platform = "GithubPages"
language = { Python = {} }
deployment = "Kubernetes"
